# Nixpacks configuration for Railway
# This tells Railway how to build and deploy your Django app

[phases.setup]
nixPkgs = ["python312", "postgresql", "gcc", "libpq-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --worker-class gevent --timeout 120 --max-requests 1000"

[variables]
DJANGO_SETTINGS_MODULE = "config.settings.production"
