# Railway deployment configuration
# This file tells Railway how to deploy your Django app

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/services/categories/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables (set these in Railway dashboard)
[env]
DJANGO_SETTINGS_MODULE = "config.settings.production"
