# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING_ADMIN_ASSIGNMENT', 'Pending Admin Assignment'),
                    ('PENDING_ESTIMATION', 'Pending Estimation'),
                    ('ESTIMATION_SUBMITTED', 'Estimation Submitted'),
                    ('AWAITING_CLIENT_APPROVAL', 'Awaiting Client Approval'),
                    ('PAYMENT_COMPLETED', 'Payment Completed'),
                    ('IN_PROGRESS', 'In Progress'),
                    ('COMPLETED', 'Completed'),
                    ('CLIENT_REVIEWED', 'Client Reviewed'),
                    ('CANCELLED', 'Cancelled'),
                    ('ASSIGNED_TO_SERVICEMAN', 'Assigned to Serviceman'),
                    ('SERVICEMAN_INSPECTED', 'Serviceman Inspected'),
                    ('NEGOTIATING', 'Negotiating'),
                    ('AWAITING_PAYMENT', 'Awaiting Payment'),
                    ('PAYMENT_CONFIRMED', 'Payment Confirmed'),
                ],
                max_length=32
            ),
        ),
    ]

